labs/lab 8/Hospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patients.urls', namespace='patients')),  # تضمين مسارات تطبيق patients
    path('doctors/', include('Doctors.urls', namespace='doctors')),
    path('', include('user.urls', namespace='user')),
    path('api/doctors/', include('Doctors.urls', namespace='doctors')),
    path("api/token/", TokenObtainPairView.as_view()),
    # path('grappelli', include('grappelli.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

labs/lab 8/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'  # هذا السطر يعرّف الـ namespace الخاص بالتطبيق

urlpatterns = [
    path('', views.home, name='home'),
    path('patients/', views.patients_home, name='patients_home'),
    path('create/', views.patients_create, name='create'),
    path('show/', views.patients_list, name='show'),
    path('success/', views.message_success, name='message_success'),
    path('error/', views.error_page, name='error_page'),
    path('show/<int:pk>/', views.patients_show_detail, name='showdetail'),  # تأكد من تصحيح اسم الدالة
    path('update/<int:pk>/', views.patients_edit, name='edit'),
    path('delete/<int:pk>/', views.patient_delete, name='delete'),
    path('forms/', views.show_forms, name='forms'),
]

labs/lab 8/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.userlogin, name='login'),
    path('register/', views.register, name='register'),
    path('logout/   ', views.userlogout, name='logout'),
]

labs/lab 8/patients/models.py
from django.db import models

# Create your models here.
class Patients(models.Model):
    first_name = models.CharField(max_length=30, default="Unknown")
    last_name = models.CharField(max_length=30, default="Unknown")
    age = models.PositiveIntegerField(default=18)
    image = models.ImageField(upload_to='images/%Y/%m/%d', null=True)
    file_report = models.FileField(upload_to='files/%Y/%m/%d', null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True)
    report = models.TextField(max_length=200)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

labs/lab 8/patients/forms.py
from django import forms
from .models import Patients

# # الطريقة الثانية لإنشاء form
# class PatientsForm(forms.ModelForm):
#     first_name = forms.CharField(label="First Name", widget=forms.TextInput(), required=True, initial='patients', help_text="This Is The First Name")
#     second_name = forms.CharField(label="Second Name", widget=forms.TextInput(), required=True, initial='patients', help_text="This Is The Second Name")
#     age = forms.IntegerField(label="age", widget=forms.NumberInput(), required=True, initial=20)
#     image = forms.ImageField(label="Image", widget=forms.FileInput())
#     file_report = forms.FileField(label="file report", widget=forms.FileInput())
#     report = forms.CharField(label="report", widget=forms.Textarea())

#     class Meta:
#         model = Patients  # تأكد من أنك تستخدم النموذج المجيد
#         fields = ['first_name', 'second_name', 'age', 'image', 'file_report', 'report']


# طريقة لإنشاء form
class PatientsForm(forms.ModelForm):
    class Meta:
        model = Patients  # تحديد الـ model الذي سيتم العمل معه
        # fields = '__all__'  # إذا كنت تريد التعامل مع كل الحقول
        fields = ['first_name', 'last_name', 'age', 'report']  # تحديد الحقول التي نريد العمل معها
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'report': forms.Textarea(attrs={'class': 'form-control'}),
        }

labs/lab 8/patients/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .models import Patients
from .forms import PatientsForm
import os
from user.decorators import isadmin
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.urls import reverse
# Create your views here.


@login_required(login_url="user:login")
def home(request):
    return render(request,'home.html')
@login_required(login_url="user:login")
def patients_home(request):
    return render(request,'patients_home.html')
@login_required(login_url="user:login")
def patients_list(request):
    patients=Patients.objects.all()
    if patients.exists:
        return render(request,'patients_list.html',{'patients':patients})

def message_success(request):
    return render(request,"patients/success_message.html")

def error_page(request):
    return render(request,"patients/error_page.html")
@login_required(login_url="user:login")
def patients_show_detail(request, pk):
    patient = get_object_or_404(Patients, id=pk)
    return render(request, 'patient_info.html', {"patient": patient})
@login_required(login_url="user:login")
# دالة حذف البيانات
def patient_delete(request, pk):
    try:
        patient = get_object_or_404(Patients, pk=pk)
        # حذف الصورة إذا كانت موجودة
        if patient.image:
            image_path = patient.image.path
            if os.path.isfile(image_path):
                os.remove(image_path)
                
        # حذف ملف التقرير إذا كان موجودًا
        if patient.file_report:
            file_report_path = patient.file_report.path
            if os.path.isfile(file_report_path):
                os.remove(file_report_path)
                
        # حذف المريض من قاعدة البيانات
        patient.delete()
        return redirect(reverse('patients:message_success'))
    except:
        return redirect(reverse('patients:error_page'))


@isadmin
# دالة إضافة البيانات
def patients_create(request):
    if request.method == 'POST':
        try:
            patient = Patients.objects.create(
                first_name=request.POST.get('fname'),
                last_name=request.POST.get('lname'),
                age=request.POST.get('age'),
                report=request.POST.get('report'),
                image=request.FILES.get('image'),
                file_report=request.FILES.get('medicalreport')
            )
            return redirect(reverse('patients:message_success'))
        except IntegrityError:
            return redirect(reverse('patients:error_page'))
    else:
        return render(request, 'patients_create.html')
@login_required(login_url="user:login")
# دالة تعديل البيانات
def patients_edit(request, pk):
    patient = get_object_or_404(Patients, id=pk)
    if request.method == 'POST':
        try:
            if patient.image:
                image_path = patient.image.path
                if os.path.isfile(image_path):
                    os.remove(image_path)
            patient.first_name = request.POST.get('fname')
            patient.last_name = request.POST.get('lname')
            patient.age = request.POST.get('age')
            patient.report = request.POST.get('report')
            patient.image = request.FILES.get('image')
            patient.file_report = request.FILES.get('medicalreport')
            patient.save()
            return redirect(reverse('patients:message_success'))
        except IntegrityError:
            return redirect(reverse('patients:error_page'))
    else:
        return render(request, 'patients_update.html', {'patient': patient})

@login_required(login_url="user:login")
def show_forms(request):
    if request.method == 'POST':
        patient_form = PatientsForm(request.POST, request.FILES)
        if patient_form.is_valid():
            patient_form.save()
            return HttpResponse('Created')
        else:
            return HttpResponse('Field!')
    else:
        patient_form = PatientsForm()
        return render(request, 'other_type_forms.html', {'form': patient_form})

labs/lab 8/templates/patients/error_page.html
{% include 'layout/header.html' %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
        <use xlink:href="#exclamation-triangle-fill" />
    </svg>
    <div>
        Operation Faild
    </div>
    <hr>
    <div>
        <a href="{% url 'patients:home' %}" class="btn btn-primary">Go Home</a>
        <a href="{% url 'patients:create' %}" class="btn btn-primary">Add More</a>
    </div>
</div>

labs/lab 8/templates/patients/patient_info.html
{% extends 'base.html' %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'patients:patients_home' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'patients:show' %}">Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'patients:create' %}">Add New Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'patients:forms' %}">Forms</a>
    </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}


{% endblock navbar %}

    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'patients:patients_home' %}">Patients</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'patients:show' %}">Show Patients</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">{{patient}}</a></li>
    {% endblock breadcrumb %}


{% block content %}
    <div class="card mb-3 border border-primary m-5 p-5">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{patient.image.url}}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{patient.id}}->{{patient}}</h5>
                <p class="card-text">age:{{patient.age}}<br>report:{{patient.report}}</p>
                <p class="card-text"><small class="text-muted"> {{patient.uploaded_at}}</small></p>
                <p class="card-text">
                    <small class="text-muted">
                        <button type="button" class="btn btn-primary"><a href="{% url 'patients:edit' patient.id %}"
                                class="text-decoration-none text-white">Update</a>
                        </button>
                        <button type="button" class="btn btn-danger">
                            <a href="{% url 'patients:delete' patient.id%}"
                                class="text-decoration-none text-white">Delete</a>
                        </button>
                        <button type="button" class="btn btn-primary"><a href="{% url 'patients:patients_home'%}"
                                class="text-decoration-none text-white">Home</a>
                        </button>
                    </small>
                </p>

            </div>
        </div>
    </div>
</div>
{% endblock content %}
    

labs/lab 8/templates/patients/patients_create.html
{% extends 'base.html' %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'patients:patients_home' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'patients:show' %}">Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'patients:create' %}">Add New Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'patients:forms' %}">Forms</a>
    </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}


{% endblock navbar %}



    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'patients:patients_home' %}">Patients</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">Add Patients</a></li>
    {% endblock breadcrumb %}

{% block content %}
<h1 class="border border-primary m-5 p-5">Add New Item</h1>
<div class="m-5 border-primary">
    <form method="post" action="{% url 'patients:create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="col-md-4">
            <label for="validationCustom01" class="form-label">First name</label>
            <input type="text" class="form-control" id="validationCustom01" required name="fname">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        
        <div class="col-md-4">
            <label for="validationCustom02" class="form-label">Last name</label>
            <input type="text" class="form-control" id="validationCustom02" required name="lname">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        
        <div class="col-md-3">
            <label for="validationDefault05" class="form-label">Age</label>
            <input type="number" class="form-control" id="validationDefault05" required name="age">
        </div>
        
        <div class="input-group">
            <span class="input-group-text">With textarea</span>
            <textarea class="form-control" aria-label="With textarea" name="report"></textarea>
        </div>
        
        <div class="mb-3">
            <label for="formFile" class="form-label">Medical Report</label>
            <input class="form-control" type="file" id="formFile" name="medicalreport">
        </div>
        
        <div class="mb-3">
            <label for="formFile" class="form-label">Patient Image</label>
            <input class="form-control" type="file" id="formImage" name="image">
        </div>
        
        <button type="submit" class="btn btn-primary m-2">Submit</button>
    </form>
</div>
{% endblock %}

labs/lab 8/templates/patients/patients_home.html
{% extends 'base.html' %}

{% block navbar %}
    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'patients:patients_home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'patients:show' %}">Patients</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'patients:create' %}">Add New Patients</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'patients:forms' %}">Forms</a>
                </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}


{% endblock navbar %}



    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">Patients</a></li>
    {% endblock breadcrumb %}

{% block content %}
    <div class="border border-primary m-5 p-5">
    {% if request.user.is_authenticated  %}
    <h1>Welcome For You {{request.user}}</h1>
    {% else %}
    <h1>Welcome For You Guest</h1>

    {% endif %}
    <h3>
        This Page For Patients
    </h3>
        </div>
{% endblock content %}
    

labs/lab 8/templates/patients/patients_list.html
{% extends 'base.html' %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'patients:patients_home' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'patients:show' %}">Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'patients:create' %}">Add New Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'patients:forms' %}">Forms</a>
    </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}


{% endblock navbar %}

    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'patients:patients_home' %}">Patients</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">Show Patients</a></li>
    {% endblock breadcrumb %}

{% block content %}
    <h1 class="border border-primary m-5 p-5">Patients</h1>
    <table class="table table-striped">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Report</th>
            <th>Actions</th>
        </tr>
        {% for patient in patients %}
        <tr>
            <td>{{ patient }}</td>
            <td>{{ patient.age }}</td>
            <td>{{ patient.report }}</td>
            <td>
                <a href="{% url 'patients:edit' patient.id %}"><i class="fas fa-edit"></i></a>
                <a href="{% url 'patients:delete' patient.id %}" class="text-danger"><i class="fas fa-trash-alt"></i></a>
                <a href="{% url 'patients:showdetail' patient.id %}" class="text-warning"><i class="fas fa-info-alt"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

labs/lab 8/templates/patients/patients_update.html
{% extends 'base.html' %}



{% block navbar %}
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'patients:patients_home' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'patients:show' %}">Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'patients:create' %}">Add New Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'patients:forms' %}">Forms</a>
    </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}


{% endblock navbar %}



{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a  href="{% url 'patients:patients_home' %}">Patients</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'patients:show' %}">Show Patients</a></li>
    <li class="breadcrumb-item active"><a class="text-muted" href="#">Update Patients</a></li>
{% endblock breadcrumb %}



{% block content %}
<h1 class="border border-primary m-5 p-5">Update Patients</h1>
<div class="m-5 border-primary">
    <form method="post" action="{% url 'patients:edit' patient.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-4">
            <label for="validationCustom01" class="form-label">First name</label>
            <input type="text" class="form-control" id="validationCustom01" required name="fname" value="{{patient.first_name}}">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        <div class="col-md-4">
            <label for="validationCustom02" class="form-label">Last name</label>
            <input type="text" class="form-control" id="validationCustom02" required name="lname" value="{{patient.last_name}}">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        <div class="col-md-3">
            <label for="validationDefault05" class="form-label">Age</label>
            <input type="number" class="form-control" id="validationDefault05" required name="age" value="{{patient.age}}">
        </div>
        <div class="input-group">
            <span class="input-group-text">With textarea</span>
            <textarea class="form-control" aria-label="With textarea" name="report">{{patient.report}}</textarea>
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">Medical Report</label>
            <input class="form-control" type="file" id="formFile" name="medicalreport" value="{{patient.file}}">
        </div>
        <div class="mb-3">
            <label for="formImage" class="form-label">Patient Image</label>
            <input class="form-control" type="file" id="formImage" name="image" value="{{patient.image}}">
        </div>
        <button type="submit" class="btn btn-primary m-2">Submit</button>
    </form>
</div>
{% endblock %}

labs/lab 8/templates/patients/success_message.html
{% include 'layout/header.html' %}
<div class="card">
    <h5 class="card-header">Message</h5>
    <div class="card-body">
        <h5 class="card-title">Done</h5>
        <p class="card-text">The Operation is Successfully</p>
        <a href="{% url 'patients:home' %}" class="btn btn-primary">Go Home</a>
        <a href="{% url 'patients:create' %}" class="btn btn-primary">Add More</a>
        <a href="{% url 'patients:show' %}" class="btn btn-primary">patients List</a>
    </div>
</div>