labs/lab 8/Doctors/urls.py
from django.urls import path
from . import views

app_name = 'doctors'  # هذا السطر يعرّف الـ namespace الخاص بالتطبيق

urlpatterns = [
    path('', views.doctors_home, name='doctors_home'),
    path('api/', views.doctor_list, name='api'),
    path('show/', views.doctors_list, name='show'),
    path('update/<int:pk>/', views.doctors_edit, name='edit'),
    path('success/', views.success_message, name='success_message'),
    path('error/', views.error_page, name='error_page'),
    path('delete/<int:pk>/', views.doctors_delete, name='delete'),
    path('show/<int:pk>/', views.doctors_show_detail, name='showdetail'),  # تأكد من تصحيح اسم الدالة
    path('create/', views.doctors_create, name='create'),
    path('forms/', views.show_forms, name='forms'),
    path("<int:doctor_id>/", views.doctor_detail, name="doctor_detail"),
]

labs/lab 8/Hospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patients.urls', namespace='patients')),  # تضمين مسارات تطبيق patients
    path('doctors/', include('Doctors.urls', namespace='doctors')),
    path('', include('user.urls', namespace='user')),
    path('api/doctors/', include('Doctors.urls', namespace='doctors')),
    path("api/token/", TokenObtainPairView.as_view()),
    # path('grappelli', include('grappelli.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

labs/lab 8/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'  # هذا السطر يعرّف الـ namespace الخاص بالتطبيق

urlpatterns = [
    path('', views.home, name='home'),
    path('patients/', views.patients_home, name='patients_home'),
    path('create/', views.patients_create, name='create'),
    path('show/', views.patients_list, name='show'),
    path('success/', views.message_success, name='message_success'),
    path('error/', views.error_page, name='error_page'),
    path('show/<int:pk>/', views.patients_show_detail, name='showdetail'),  # تأكد من تصحيح اسم الدالة
    path('update/<int:pk>/', views.patients_edit, name='edit'),
    path('delete/<int:pk>/', views.patient_delete, name='delete'),
    path('forms/', views.show_forms, name='forms'),
]

labs/lab 8/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.userlogin, name='login'),
    path('register/', views.register, name='register'),
    path('logout/   ', views.userlogout, name='logout'),
]

labs/lab 8/Doctors/models.py
from django.db import models

# Create your models here.
class Doctors(models.Model):
    first_name = models.CharField(max_length=30, default="Unknown")
    last_name = models.CharField(max_length=30, default="Unknown")
    age = models.PositiveIntegerField(default=18)
    Specialization=models.CharField(max_length=50,default="Unknown")
    image = models.ImageField(upload_to='images/%Y/%m/%d', null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

labs/lab 8/Doctors/forms.py
from django import forms
from .models import Doctors


class DoctorsForm(forms.ModelForm):
    class Meta:
        model = Doctors  # تحديد الـ model الذي سيتم العمل معه
        # fields = '__all__'  # إذا كنت تريد التعامل مع كل الحقول
        fields = ['first_name', 'last_name', 'age', 'Specialization']  # تحديد الحقول التي نريد العمل معها
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'Specialization': forms.TextInput(attrs={'class': 'form-control'}),
        }

labs/lab 8/Doctors/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from django.http import HttpResponse
from django.db import IntegrityError
from .models import Doctors
from django.contrib.auth.decorators import login_required
from .forms import DoctorsForm
import os
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status
from .serializers import DoctorSerializer
from rest_framework.permissions import IsAuthenticated, IsAdminUser
# Create your views here.
@login_required(login_url="user:login")
def doctors_home(request):
    return render(request,"doctors_home.html")
@login_required(login_url="user:login")
def doctors_list(request):
    doctors=Doctors.objects.all()
    if doctors.exists:
        return render(request,"doctors_lits.html",{'doctors':doctors})
    
@login_required(login_url="user:login")
def doctors_edit(request, pk):
    doctor = get_object_or_404(Doctors, id=pk)
    if request.method == 'POST':
        try:
            if doctor.image:
                image_path = doctor.image.path
                if os.path.isfile(image_path):
                    os.remove(image_path)
            doctor.first_name = request.POST.get('fname')
            doctor.last_name = request.POST.get('lname')
            doctor.age = request.POST.get('age')
            doctor.Specialization = request.POST.get('Specialization')
            doctor.image = request.FILES.get('image')
            doctor.save()
            return redirect(reverse('doctors:success_message'))
        except IntegrityError:
            return redirect(reverse('doctors:error_page'))
    else:
        return render(request, 'doctors_update.html', {'doctor': doctor})

@login_required(login_url="user:login")
def doctors_delete(request, pk):
    try:
        doctor = get_object_or_404(Doctors, pk=pk)
        # حذف الصورة إذا كانت موجودة
        if doctor.image:
            image_path = doctor.image.path
            if os.path.isfile(image_path):
                os.remove(image_path)
        doctor.delete()
        return redirect(reverse('doctors:success_message'))
    except:
        return redirect(reverse('doctors:error_page'))

@login_required(login_url="user:login")
def doctors_show_detail(request, pk):
    doctor = get_object_or_404(Doctors, id=pk)
    return render(request, 'doctors_info.html', {"doctor": doctor})
@login_required(login_url="user:login")
def doctors_create(request):
    if request.method == 'POST':
        try:
            doctor = Doctors.objects.create(
                first_name=request.POST.get('fname'),
                last_name=request.POST.get('lname'),
                age=request.POST.get('age'),
                Specialization=request.POST.get('Specialization'),
                image=request.FILES.get('image'),
            )
            return redirect(reverse('doctors:success_message'))
        except IntegrityError:
            return redirect(reverse('doctors:error_page'))
    else:
        return render(request, 'doctors_create.html')


def success_message(request):
    return render(request,"doctors/success_message.html")

def error_page(request):
    return render(request,"doctors/error_page.html")
@login_required(login_url="user:login")
def show_forms(request):
    if request.method == 'POST':
        doctor_form = DoctorsForm(request.POST)
        if doctor_form.is_valid():
            doctor_form.save()
            return HttpResponse('Created')
        else:
            return HttpResponse('Field!')
    else:
        doctor_form = DoctorsForm()
        return render(request, 'doctors_forms.html', {'form': doctor_form})


@api_view(["GET", "POST"])
def doctor_list(request):
    if request.method == "GET":
        try:
            doctors = Doctors.objects.all()
            serializer = DoctorSerializer(doctors, many=True)
            return Response(serializer.data)
        except Exception as e:
            return Response(
                {"error": f"An error while retrieving doctors list: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )
    
    elif request.method == "POST":
        try:
            serializer = DoctorSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(
                    {
                        "message": "Data added successfully",
                        "status": status.HTTP_201_CREATED,
                    },
                    status=status.HTTP_201_CREATED,
                )
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response(
                {"error": f"An error while saving the doctor: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

@api_view(["GET", "PUT", "DELETE"])
def doctor_detail(request, doctor_id):
    try:
        doctor = get_object_or_404(Doctors, id=doctor_id)
    except Exception as e:
        return Response(
            {"error": f"Doctor not found: {str(e)}"},
            status=status.HTTP_404_NOT_FOUND,
        )

    if request.method == "GET":
        try:
            serializer = DoctorSerializer(doctor)
            return Response(serializer.data)
        except Exception as e:
            return Response(
                {"error": f"An error while retrieving doctor data: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )
    elif request.method == "PUT":
        try:
            serializer = DoctorSerializer(doctor, data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response(
                {"error": f"An error while updating doctor data: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

    elif request.method == "DELETE":
        try:
            doctor.delete()
            return Response(
                {"message": "Doctor deleted successfully"},
                status=status.HTTP_204_NO_CONTENT,
            )
        except Exception as e:
            return Response(
                {"error": f"An error while deleting doctor data: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

labs/lab 8/templates/doctors/doctors_create.html
{% extends 'base.html' %}


{% block navbar %}
    <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'doctors:doctors_home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'doctors:show' %}">Doctors</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link active" href="{% url 'doctors:create' %}">Add New Doctor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:forms' %}">Forms</a>
                </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}

{% endblock navbar %}


    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'doctors:doctors_home' %}">doctors</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">Add doctors</a></li>
    {% endblock breadcrumb %}

{% block content %}
<h1 class="border border-primary m-5 p-5">Add New Doctor</h1>
<div class="m-5 border-primary">
    <form method="post" action="{% url 'doctors:create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="col-md-4">
            <label for="validationCustom01" class="form-label">First name</label>
            <input type="text" class="form-control" id="validationCustom01" required name="fname">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        
        <div class="col-md-4">
            <label for="validationCustom02" class="form-label">Last name</label>
            <input type="text" class="form-control" id="validationCustom02" required name="lname">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        
        <div class="col-md-3">
            <label for="validationDefault05" class="form-label">Age</label>
            <input type="number" class="form-control" id="validationDefault05" required name="age">
        </div>
        
        <div class="input-group">
            <span class="input-group-text">Specialization</span>
            <input type="text" class="form-control" aria-label="With textarea" name="Specialization"></input>
        </div>
        
        
        <div class="mb-3">
            <label for="formFile" class="form-label">Patient Image</label>
            <input class="form-control" type="file" id="formImage" name="image">
        </div>
        
        <button type="submit" class="btn btn-primary m-2">Submit</button>
    </form>
</div>
{% endblock %}

labs/lab 8/templates/doctors/doctors_forms.html
{% extends 'base.html' %}


{% block navbar %}
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'doctors:doctors_home' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'doctors:show' %}">Doctors</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'doctors:create' %}">Add New Doctors</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'doctors:forms' %}">Forms</a>
    </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}


{% endblock navbar %}


    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'doctors:doctors_home' %}">doctors</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">Forms</a></li>
    {% endblock breadcrumb %}

{% block content %}
<h1 class="border border-primary m-5 p-5">Add Doctor</h1>
<div class="m-5 border-primary">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary m-2">Submit</button>
    </form>
</div>
{% endblock %}

labs/lab 8/templates/doctors/doctors_home.html
{% extends 'base.html' %}

{% block navbar %}
    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'doctors:doctors_home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'doctors:show' %}">Doctors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:create' %}">Add New Doctors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:forms' %}">Forms</a>
                </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}


{% endblock navbar %}



    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">Doctors</a></li>
    {% endblock breadcrumb %}

{% block content %}
    <div class="border border-primary m-5 p-5">
    {% if request.user.is_authenticated  %}
    <h1>Welcome For You {{request.user}}</h1>
    {% else %}
    <h1>Welcome For You Guest</h1>

    {% endif %}
    <h3>
        This Page For Doctors
    </h3>
        </div>
{% endblock content %}
    

labs/lab 8/templates/doctors/doctors_info.html
{% extends 'base.html' %}
{% block navbar %}
    <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'doctors:doctors_home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'doctors:show' %}">Doctors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:create' %}">Add New Doctor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:forms' %}">Forms</a>
                </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}

{% endblock navbar %}

    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'doctors:doctors_home' %}">Doctors</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'doctors:show' %}">Show Doctors</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">{{doctor}}</a></li>
    {% endblock breadcrumb %}


{% block content %}
    <div class="card mb-3 border border-primary m-5 p-5">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{doctor.image.url}}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{doctor.id}}->{{doctor}}</h5>
                <p class="card-text">age: {{doctor.age}}<br>Specialization: {{doctor.Specialization}}</p>
                <p class="card-text"><small class="text-muted"> {{patient.uploaded_at}}</small></p>
                <p class="card-text">
                    <small class="text-muted">
                        <button type="button" class="btn btn-primary"><a href="{% url 'doctors:edit' doctor.id %}"
                                class="text-decoration-none text-white">Update</a>
                        </button>
                        <button type="button" class="btn btn-danger">
                            <a href="{% url 'doctors:delete' doctor.id%}"
                                class="text-decoration-none text-white">Delete</a>
                        </button>
                        <button type="button" class="btn btn-primary"><a href="{% url 'doctors:doctors_home'%}"
                                class="text-decoration-none text-white">Home</a>
                        </button>
                    </small>
                </p>

            </div>
        </div>
    </div>
</div>
{% endblock content %}
    

labs/lab 8/templates/doctors/doctors_lits.html
{% extends 'base.html' %}


{% block navbar %}
        <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'patients:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'doctors:show' %}">Doctors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:create' %}">Add New Doctors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:forms' %}">Forms</a>
                </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}

{% endblock navbar %}


    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'doctors:doctors_home' %}">Doctors</a></li>
        <li class="breadcrumb-item active"><a class="text-muted" href="#">Show Doctors</a></li>
    {% endblock breadcrumb %}

{% block content %}
    <h1 class="border border-primary m-5 p-5">Doctors</h1>
    <table class="table table-striped">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Specialization</th>
        </tr>
        {% for doctor in doctors %}
        <tr>
            <td>{{ doctor }}</td>
            <td>{{ doctor.age }}</td>
            <td>{{ doctor.Specialization }}</td>
            <td>
                <a href="{% url 'doctors:edit' doctor.id %}"><i class="fas fa-edit"></i></a> 
                <a href="{% url 'doctors:delete' doctor.id %}" class="text-danger"><i class="fas fa-trash-alt"></i></a>
                <a href="{% url 'doctors:showdetail' doctor.id %}" class="text-warning"><i class="fas fa-info-alt"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

labs/lab 8/templates/doctors/doctors_update.html
{% extends 'base.html' %}

{% block navbar %}
    <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'doctors:doctors_home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'doctors:show' %}">Doctors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:create' %}">Add New Doctor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:forms' %}">Forms</a>
                </li>
{% if request.user.is_staff %}
<li class="nav-item">
    <a class="nav-link" href="/admin/">Admin</a>
</li>
{% endif %}

{% endblock navbar %}

    {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'patients:home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'doctors:doctors_home' %}">Doctors</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'doctors:show' %}">Show Doctors</a></li>
        <li class="breadcrumb-item "><a class="text-muted" href="#">Update Doctors</a></li>
    {% endblock breadcrumb %}



{% block content %}
<h1 class="border border-primary m-5 p-5">Update Doctors</h1>
<div class="m-5 border-primary">
    <form method="post" action="{% url 'doctors:edit' doctor.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-4">
            <label for="validationCustom01" class="form-label">First name</label>
            <input type="text" class="form-control" id="validationCustom01" required name="fname" value="{{doctor.first_name}}">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        <div class="col-md-4">
            <label for="validationCustom02" class="form-label">Last name</label>
            <input type="text" class="form-control" id="validationCustom02" required name="lname" value="{{doctor.last_name}}">
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
        <div class="col-md-3">
            <label for="validationDefault05" class="form-label">Age</label>
            <input type="number" class="form-control" id="validationDefault05" required name="age" value="{{doctor.age}}">
        </div>
        <div class="col-md-3">
            <label for="validationDefault05" class="form-label">Specialization</label>
            <input type="text" class="form-control" id="validationDefault05" required name="Specialization" value="{{doctor.Specialization}}">
        </div>
        <div class="mb-3">
            <label for="formImage" class="form-label">Doctor Image</label>
            <input class="form-control" type="file" id="formImage" name="image" value="{{doctor.image}}">
        </div>
        <button type="submit" class="btn btn-primary m-2">Submit</button>
    </form>
</div>
{% endblock %}

labs/lab 8/templates/doctors/error_page.html
{% include 'layout/header.html' %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
        <use xlink:href="#exclamation-triangle-fill" />
    </svg>
    <div>
        Operation Faild
    </div>
    <hr>
    <div>
        <a href="{% url 'doctors:doctors_home' %}" class="btn btn-primary">Go Home</a>
        <a href="{% url 'doctors:create' %}" class="btn btn-primary">Add More</a>
    </div>
</div>

labs/lab 8/templates/doctors/success_message.html
{% include 'layout/header.html' %}
<div class="card">
    <h5 class="card-header">Message</h5>
    <div class="card-body">
        <h5 class="card-title">Done</h5>
        <p class="card-text">The Operation is Successfully</p>
        <a href="{% url 'doctors:doctors_home' %}" class="btn btn-primary">Go Home</a>
        <a href="{% url 'doctors:create' %}" class="btn btn-primary">Add More</a>
        <a href="{% url 'doctors:show' %}" class="btn btn-primary">Doctors List</a>
    </div>
</div>